"""
=============================================================
DFRA Log Retention & Preservation Observation Library Builder
=============================================================

Purpose:
--------
Append enterprise-grade DFRA Log Retention & Preservation
observations into the central Observation Repository.

Repository:
dataset/observation_library.xlsx

Author:
B.Tech Major Project
Intelligent Security Analytics
=============================================================
"""

import pandas as pd
from pathlib import Path


# ============================================================
# Configuration
# ============================================================

DOMAIN = "Log Retention & Preservation"
ACTIVITY = "DFRA"

ROOT_DIR = Path(__file__).resolve().parent.parent

DATASET_FILE = ROOT_DIR / "dataset" / "observation_library.xlsx"


# ============================================================
# Repository Validation
# ============================================================

if not DATASET_FILE.exists():

    raise FileNotFoundError(

        "\nObservation Repository not found.\n\n"
        "Please execute:\n"
        "build_user_management_library.py\n"
        "before running this script."

    )


# ============================================================
# Load Repository
# ============================================================

existing_df = pd.read_excel(DATASET_FILE)

existing_count = len(existing_df)


# ============================================================
# DFRA Log Retention & Preservation Observations
# ============================================================

OBSERVATIONS = [

    {
        "Activity": ACTIVITY,
        "Domain": DOMAIN,
        "Observation":
        "Verification of enterprise log retention identified that security logs generated by critical production systems were not retained in accordance with approved regulatory and forensic retention requirements. Inadequate retention periods reduce the availability of digital evidence during delayed incident investigations.",
        "Severity": "High"
    },

    {
        "Activity": ACTIVITY,
        "Domain": DOMAIN,
        "Observation":
        "Assessment of log preservation identified that archived security logs were stored within repositories that permitted modification or deletion by privileged administrators. Lack of immutable storage increases the risk of evidence tampering and compromises forensic integrity.",
        "Severity": "High"
    },

    {
        "Activity": ACTIVITY,
        "Domain": DOMAIN,
        "Observation":
        "Analysis of evidence preservation identified that automated log deletion processes were not supported by documented management approvals or retention validation procedures. Improper deletion controls increase the likelihood of permanent loss of forensic evidence.",
        "Severity": "High"
    },

    {
        "Activity": ACTIVITY,
        "Domain": DOMAIN,
        "Observation":
        "Inspection of log archival identified that security logs from critical applications and infrastructure were not archived upon completion of active retention periods, limiting long-term availability of digital evidence.",
        "Severity": "High"
    },

    {
        "Activity": ACTIVITY,
        "Domain": DOMAIN,
        "Observation":
        "Review of secure log storage identified that archived forensic logs were not protected using appropriate access restrictions and storage security controls. Weak storage protection increases the risk of unauthorized access or evidence manipulation.",
        "Severity": "High"
    },

    {
        "Activity": ACTIVITY,
        "Domain": DOMAIN,
        "Observation":
        "Validation of evidence preservation identified that backup copies of archived security logs were not maintained to support recovery following storage failures or accidental deletion.",
        "Severity": "High"
    },

    {
        "Activity": ACTIVITY,
        "Domain": DOMAIN,
        "Observation":
        "Assessment of log retention governance identified that high-risk log preservation exceptions remained active beyond approved remediation timelines without documented risk acceptance or compensating security controls.",
        "Severity": "High"
    },

    {
        "Activity": ACTIVITY,
        "Domain": DOMAIN,
        "Observation":
        "Analysis of forensic storage identified that archived security logs were not protected using tamper-resistant or write-protected storage mechanisms appropriate for digital evidence preservation.",
        "Severity": "High"
    },

    {
        "Activity": ACTIVITY,
        "Domain": DOMAIN,
        "Observation":
        "Verification of retention schedules identified that enterprise log retention schedules were not periodically reviewed to ensure continued alignment with business, legal and regulatory obligations.",
        "Severity": "Medium"
    },

    {
        "Activity": ACTIVITY,
        "Domain": DOMAIN,
        "Observation":
        "Assessment of archived evidence identified that integrity of archived log repositories was not periodically verified to confirm continued availability and readability of retained forensic evidence.",
        "Severity": "Medium"
    },

    {
        "Activity": ACTIVITY,
        "Domain": DOMAIN,
        "Observation":
        "Inspection of evidence preservation identified that log archival activities were not consistently documented to demonstrate successful preservation of security events generated by critical systems.",
        "Severity": "Medium"
    },

    {
        "Activity": ACTIVITY,
        "Domain": DOMAIN,
        "Observation":
        "Review of log lifecycle management identified that archived security logs exceeding approved retention periods were not securely disposed of through documented evidence destruction procedures.",
        "Severity": "Medium"
    },

    {
        "Activity": ACTIVITY,
        "Domain": DOMAIN,
        "Observation":
        "Validation of forensic repositories identified that storage capacity for archived security logs was not periodically reviewed, increasing the likelihood of evidence loss due to storage limitations.",
        "Severity": "Medium"
    },

    {
        "Activity": ACTIVITY,
        "Domain": DOMAIN,
        "Observation":
        "Assessment of log preservation identified that preservation procedures for cloud-hosted log repositories had not been formally established to support forensic investigations involving cloud environments.",
        "Severity": "Medium"
    },

    {
        "Activity": ACTIVITY,
        "Domain": DOMAIN,
        "Observation":
        "Analysis of Log Retention & Preservation governance identified that enterprise log preservation standards had not undergone periodic review to address evolving regulatory obligations, forensic requirements and enterprise technology changes.",
        "Severity": "Medium"
    },

        {
        "Activity": ACTIVITY,
        "Domain": DOMAIN,
        "Observation":
        "Verification of log retention reviews identified that enterprise log retention requirements had not undergone periodic business owner recertification to ensure continued alignment with forensic investigation objectives and regulatory obligations.",
        "Severity": "Medium"
    },

    {
        "Activity": ACTIVITY,
        "Domain": DOMAIN,
        "Observation":
        "Assessment of log archival identified that archived security logs were not periodically restored and validated to confirm successful recovery of preserved forensic evidence.",
        "Severity": "Medium"
    },

    {
        "Activity": ACTIVITY,
        "Domain": DOMAIN,
        "Observation":
        "Analysis of evidence preservation identified that archived log repositories located at alternate storage sites were not periodically reviewed to validate continued accessibility and integrity of preserved digital evidence.",
        "Severity": "Medium"
    },

    {
        "Activity": ACTIVITY,
        "Domain": DOMAIN,
        "Observation":
        "Inspection of secure log storage identified that privileged access to archived forensic logs was not periodically reviewed to ensure compliance with the principle of least privilege and evidence preservation requirements.",
        "Severity": "Medium"
    },

    {
        "Activity": ACTIVITY,
        "Domain": DOMAIN,
        "Observation":
        "Review of log lifecycle management identified that preservation holds for logs associated with ongoing investigations were not formally documented, increasing the risk of premature evidence deletion.",
        "Severity": "Medium"
    },

    {
        "Activity": ACTIVITY,
        "Domain": DOMAIN,
        "Observation":
        "Validation of forensic repositories identified that automated monitoring for unauthorized deletion or modification of archived log files had not been implemented across enterprise log storage environments.",
        "Severity": "Medium"
    },

    {
        "Activity": ACTIVITY,
        "Domain": DOMAIN,
        "Observation":
        "Assessment of evidence preservation governance identified that recurring log retention deficiencies identified during forensic readiness assessments were not subjected to Root Cause Analysis (RCA) or tracked through formal corrective action plans.",
        "Severity": "Medium"
    },

    {
        "Activity": ACTIVITY,
        "Domain": DOMAIN,
        "Observation":
        "Analysis of evidence preservation identified that metadata associated with archived security logs including collection source, retention period and archival timestamp was not consistently maintained to support forensic investigations.",
        "Severity": "Medium"
    },

    {
        "Activity": ACTIVITY,
        "Domain": DOMAIN,
        "Observation":
        "Inspection of forensic documentation identified that enterprise log retention procedures, archival workflows and evidence preservation responsibilities were not consistently maintained within centralized governance repositories.",
        "Severity": "Medium"
    },

    {
        "Activity": ACTIVITY,
        "Domain": DOMAIN,
        "Observation":
        "Review of management reporting identified that dashboards summarizing log retention compliance, archival success rates, preservation exceptions and unresolved forensic evidence risks were not periodically presented to Information Security management.",
        "Severity": "Medium"
    },

    {
        "Activity": ACTIVITY,
        "Domain": DOMAIN,
        "Observation":
        "Verification of Log Retention & Preservation procedures identified that documented operating procedures had not undergone periodic review and management approval.",
        "Severity": "Low"
    },

    {
        "Activity": ACTIVITY,
        "Domain": DOMAIN,
        "Observation":
        "Assessment of Log Retention & Preservation documentation identified absence of version-controlled log retention and evidence preservation standards aligned with the current enterprise technology landscape and regulatory requirements.",
        "Severity": "Low"
    },

    {
        "Activity": ACTIVITY,
        "Domain": DOMAIN,
        "Observation":
        "Analysis of awareness records identified that system administrators, security operations personnel and forensic responders were not periodically provided awareness training on enterprise log retention requirements and evidence preservation practices.",
        "Severity": "Low"
    },

    {
        "Activity": ACTIVITY,
        "Domain": DOMAIN,
        "Observation":
        "Inspection of governance records identified that periodic internal quality assurance reviews over Log Retention & Preservation activities were not evidenced.",
        "Severity": "Low"
    },

    {
        "Activity": ACTIVITY,
        "Domain": DOMAIN,
        "Observation":
        "Review of management reporting identified that enterprise Log Retention & Preservation Key Performance Indicators (KPIs) were not periodically reported to senior management for governance oversight.",
        "Severity": "Low"
    }

]

# ============================================================
# CREATE DATAFRAME
# ============================================================

new_df = pd.DataFrame(OBSERVATIONS)

# ============================================================
# APPEND TO EXISTING REPOSITORY
# ============================================================

combined_df = pd.concat(
    [existing_df, new_df],
    ignore_index=True
)

before_dedup = len(combined_df)

combined_df = combined_df.drop_duplicates(
    subset=[
        "Activity",
        "Domain",
        "Observation"
    ],
    keep="first"
)

duplicates_removed = before_dedup - len(combined_df)

combined_df = combined_df.sort_values(
    by=[
        "Activity",
        "Domain"
    ]
).reset_index(drop=True)

# ============================================================
# SAVE UPDATED REPOSITORY
# ============================================================

combined_df.to_excel(
    DATASET_FILE,
    index=False
)

# ============================================================
# EXECUTION SUMMARY
# ============================================================

print("\n===================================================")
print("DFRA Log Retention & Preservation Library Created Successfully")
print("===================================================")

print(f"\nActivity                : {ACTIVITY}")
print(f"Domain                  : {DOMAIN}")
print(f"Existing Observations   : {existing_count}")
print(f"New Observations        : {len(new_df)}")
print(f"Duplicates Removed      : {duplicates_removed}")
print(f"Final Repository Size   : {len(combined_df)}")

print(f"\nRepository Updated :\n{DATASET_FILE}")