"""
=============================================================
Logging & Monitoring Observation Library Builder
=============================================================

Purpose:
--------
Append enterprise-grade Logging & Monitoring observations
into the central Observation Repository.

Repository:
dataset/observation_library.xlsx

This script DOES NOT overwrite the repository.

It performs:

1. Load existing repository
2. Generate Logging & Monitoring observations
3. Append new observations
4. Remove duplicates
5. Save updated repository

Author:
B.Tech Major Project
Intelligent Security Analytics
=============================================================
"""

import pandas as pd
from pathlib import Path


# ============================================================
# Configuration
# ============================================================

DOMAIN = "Logging & Monitoring"
ACTIVITY = "ITGC"

ROOT_DIR = Path(__file__).resolve().parent.parent

DATASET_FILE = ROOT_DIR / "dataset" / "observation_library.xlsx"


# ============================================================
# Repository Validation
# ============================================================

if not DATASET_FILE.exists():

    raise FileNotFoundError(

        "\nObservation Repository not found.\n\n"
        "Please execute:\n"
        "build_user_management_library.py\n"
        "before running this script."

    )


# ============================================================
# Load Existing Repository
# ============================================================

existing_df = pd.read_excel(DATASET_FILE)

existing_count = len(existing_df)


# ============================================================
# Logging & Monitoring Observations
# ============================================================

OBSERVATIONS = [

    {
        "Activity": ACTIVITY,
        "Domain": DOMAIN,
        "Observation":
        "Review of application logging configurations identified that security-relevant events generated by the application were not forwarded to the centralized Security Information and Event Management (SIEM) platform. Absence of centralized log monitoring may delay detection of unauthorized activities and impact timely incident response.",
        "Severity": "High"
    },

    {
        "Activity": ACTIVITY,
        "Domain": DOMAIN,
        "Observation":
        "Review of audit logging configurations identified that successful and failed user authentication events were not consistently captured within application audit logs. Incomplete authentication logging reduces the organization's ability to investigate unauthorized access attempts.",
        "Severity": "High"
    },

    {
        "Activity": ACTIVITY,
        "Domain": DOMAIN,
        "Observation":
        "Review of privileged activity logging identified that administrative actions performed using privileged accounts were not comprehensively logged. Absence of privileged activity logs weakens accountability and limits forensic investigation capabilities.",
        "Severity": "High"
    },

    {
        "Activity": ACTIVITY,
        "Domain": DOMAIN,
        "Observation":
        "Review of log protection mechanisms identified that audit logs could be modified or deleted by application administrators without independent monitoring or integrity validation. Lack of log integrity controls increases the risk of evidence tampering.",
        "Severity": "High"
    },

    {
        "Activity": ACTIVITY,
        "Domain": DOMAIN,
        "Observation":
        "Review of security monitoring procedures identified that critical security events generated by the application were not configured to trigger automated alerts for Security Operations Center (SOC) review. Delayed identification of security incidents may increase business impact.",
        "Severity": "High"
    },

    {
        "Activity": ACTIVITY,
        "Domain": DOMAIN,
        "Observation":
        "Review of application logging configurations identified that database transaction logs associated with critical business operations were not retained in accordance with organizational security requirements. Insufficient log retention may limit investigation of security incidents.",
        "Severity": "High"
    },

    {
        "Activity": ACTIVITY,
        "Domain": DOMAIN,
        "Observation":
        "Review of log collection mechanisms identified that security logs generated by integrated application components were not consistently collected within the centralized monitoring platform. Partial log visibility may reduce overall monitoring effectiveness.",
        "Severity": "High"
    },

    {
        "Activity": ACTIVITY,
        "Domain": DOMAIN,
        "Observation":
        "Review of audit trail configurations identified that application configuration changes were not comprehensively logged. Absence of configuration change logging may prevent identification of unauthorized modifications.",
        "Severity": "High"
    },

    {
        "Activity": ACTIVITY,
        "Domain": DOMAIN,
        "Observation":
        "Review of security monitoring procedures identified that daily review of critical security logs was not evidenced for production environments. Lack of routine monitoring may delay identification of suspicious activities.",
        "Severity": "Medium"
    },

    {
        "Activity": ACTIVITY,
        "Domain": DOMAIN,
        "Observation":
        "Review of application logging standards identified that logging requirements were not formally documented for all critical application components, resulting in inconsistent logging coverage.",
        "Severity": "Medium"
    },

    {
        "Activity": ACTIVITY,
        "Domain": DOMAIN,
        "Observation":
        "Review of audit logging configurations identified that user account creation, modification and deletion activities were not consistently recorded within application audit trails.",
        "Severity": "Medium"
    },

    {
        "Activity": ACTIVITY,
        "Domain": DOMAIN,
        "Observation":
        "Review of log retention procedures identified that archived security logs were not periodically validated for successful backup and recoverability.",
        "Severity": "Medium"
    },

    {
        "Activity": ACTIVITY,
        "Domain": DOMAIN,
        "Observation":
        "Review of security monitoring reports identified absence of documented follow-up actions for recurring security alerts generated by the application environment.",
        "Severity": "Medium"
    },

    {
        "Activity": ACTIVITY,
        "Domain": DOMAIN,
        "Observation":
        "Review of logging configurations identified that audit logs did not consistently capture the originating source IP address for security-sensitive transactions.",
        "Severity": "Medium"
    },

    {
        "Activity": ACTIVITY,
        "Domain": DOMAIN,
        "Observation":
        "Review of log management procedures identified that periodic health checks over application log generation and log forwarding mechanisms were not performed.",
        "Severity": "Medium"
    },

        {
        "Activity": ACTIVITY,
        "Domain": DOMAIN,
        "Observation":
        "Review of log review procedures identified that exception reports generated from centralized monitoring tools were not periodically reviewed to validate completeness of security event analysis.",
        "Severity": "Medium"
    },

    {
        "Activity": ACTIVITY,
        "Domain": DOMAIN,
        "Observation":
        "Review of application monitoring identified that failed authorization events were not consistently monitored and escalated for security investigation.",
        "Severity": "Medium"
    },

    {
        "Activity": ACTIVITY,
        "Domain": DOMAIN,
        "Observation":
        "Review of audit logging procedures identified that privileged account password reset activities were not comprehensively logged within application audit trails.",
        "Severity": "Medium"
    },

    {
        "Activity": ACTIVITY,
        "Domain": DOMAIN,
        "Observation":
        "Review of log synchronization controls identified that application servers were not consistently synchronized with an approved enterprise time source. Inconsistent timestamps may affect event correlation during security investigations.",
        "Severity": "Medium"
    },

    {
        "Activity": ACTIVITY,
        "Domain": DOMAIN,
        "Observation":
        "Review of application monitoring identified that repeated application failures and abnormal termination events were not configured for automated security monitoring and alert generation.",
        "Severity": "Medium"
    },

    {
        "Activity": ACTIVITY,
        "Domain": DOMAIN,
        "Observation":
        "Review of audit logging identified that access to sensitive application configuration files was not consistently captured within audit logs.",
        "Severity": "Medium"
    },

    {
        "Activity": ACTIVITY,
        "Domain": DOMAIN,
        "Observation":
        "Review of security monitoring procedures identified that unresolved critical security alerts were not periodically tracked until formal closure.",
        "Severity": "Medium"
    },

    {
        "Activity": ACTIVITY,
        "Domain": DOMAIN,
        "Observation":
        "Review of log archival procedures identified that archived audit logs were not protected against unauthorized modification throughout the retention period.",
        "Severity": "Medium"
    },

    {
        "Activity": ACTIVITY,
        "Domain": DOMAIN,
        "Observation":
        "Review of centralized monitoring configurations identified that application-specific security use cases had not been implemented within the enterprise SIEM platform.",
        "Severity": "Medium"
    },

    {
        "Activity": ACTIVITY,
        "Domain": DOMAIN,
        "Observation":
        "Review of log management governance identified that ownership for periodic validation of application logging controls had not been formally assigned.",
        "Severity": "Medium"
    },

    {
        "Activity": ACTIVITY,
        "Domain": DOMAIN,
        "Observation":
        "Review of logging governance identified that periodic management reporting over application logging effectiveness was not available for review.",
        "Severity": "Low"
    },

    {
        "Activity": ACTIVITY,
        "Domain": DOMAIN,
        "Observation":
        "Review of application logging standards identified that documented logging procedures had not undergone periodic review and approval.",
        "Severity": "Low"
    },

    {
        "Activity": ACTIVITY,
        "Domain": DOMAIN,
        "Observation":
        "Review of operational procedures identified that application support personnel were not periodically provided awareness regarding logging and monitoring responsibilities.",
        "Severity": "Low"
    },

    {
        "Activity": ACTIVITY,
        "Domain": DOMAIN,
        "Observation":
        "Review of logging documentation identified absence of version-controlled operational procedures governing application log management activities.",
        "Severity": "Low"
    },

    {
        "Activity": ACTIVITY,
        "Domain": DOMAIN,
        "Observation":
        "Review of logging governance identified that periodic internal compliance reviews over application logging controls were not evidenced.",
        "Severity": "Low"
    }

]

# ============================================================
# CREATE DATAFRAME
# ============================================================

new_df = pd.DataFrame(OBSERVATIONS)

# ============================================================
# APPEND TO EXISTING REPOSITORY
# ============================================================

combined_df = pd.concat(
    [existing_df, new_df],
    ignore_index=True
)

before_dedup = len(combined_df)

combined_df = combined_df.drop_duplicates(
    subset=[
        "Activity",
        "Domain",
        "Observation"
    ],
    keep="first"
)

duplicates_removed = before_dedup - len(combined_df)

combined_df = combined_df.sort_values(
    by=[
        "Activity",
        "Domain"
    ]
).reset_index(drop=True)

# ============================================================
# SAVE UPDATED REPOSITORY
# ============================================================

combined_df.to_excel(
    DATASET_FILE,
    index=False
)

# ============================================================
# EXECUTION SUMMARY
# ============================================================

print("\n===================================================")
print("Logging & Monitoring Library Created Successfully")
print("===================================================")

print(f"\nDomain                  : {DOMAIN}")

print(f"Existing Observations   : {existing_count}")

print(f"New Observations        : {len(new_df)}")

print(f"Duplicates Removed      : {duplicates_removed}")

print(f"Final Repository Size   : {len(combined_df)}")

print(f"\nRepository Updated :\n{DATASET_FILE}")