"""
=============================================================
DFRA Evidence Logging & Event Capture Observation Library Builder
=============================================================

Purpose:
--------
Append enterprise-grade DFRA Evidence Logging & Event Capture
observations into the central Observation Repository.

Repository:
dataset/observation_library.xlsx

Author:
B.Tech Major Project
Intelligent Security Analytics
=============================================================
"""

import pandas as pd
from pathlib import Path


# ============================================================
# Configuration
# ============================================================

DOMAIN = "Evidence Logging & Event Capture"
ACTIVITY = "DFRA"

ROOT_DIR = Path(__file__).resolve().parent.parent

DATASET_FILE = ROOT_DIR / "dataset" / "observation_library.xlsx"


# ============================================================
# Repository Validation
# ============================================================

if not DATASET_FILE.exists():

    raise FileNotFoundError(

        "\nObservation Repository not found.\n\n"
        "Please execute:\n"
        "build_user_management_library.py\n"
        "before running this script."

    )


# ============================================================
# Load Repository
# ============================================================

existing_df = pd.read_excel(DATASET_FILE)

existing_count = len(existing_df)


# ============================================================
# DFRA Evidence Logging & Event Capture Observations
# ============================================================

OBSERVATIONS = [

    {
        "Activity": ACTIVITY,
        "Domain": DOMAIN,
        "Observation":
        "Verification of enterprise logging controls identified that security-relevant events generated by critical servers, applications and network infrastructure were not consistently captured within centralized logging systems. Incomplete evidence collection reduces forensic visibility during security investigations.",
        "Severity": "High"
    },

    {
        "Activity": ACTIVITY,
        "Domain": DOMAIN,
        "Observation":
        "Assessment of authentication logging identified that successful and failed user authentication events were not consistently recorded across critical information systems. Missing authentication records reduce the organization's ability to reconstruct security incidents.",
        "Severity": "High"
    },

    {
        "Activity": ACTIVITY,
        "Domain": DOMAIN,
        "Observation":
        "Analysis of privileged activity logging identified that administrator actions including account creation, privilege modifications and security configuration changes were not comprehensively logged across production environments.",
        "Severity": "High"
    },

    {
        "Activity": ACTIVITY,
        "Domain": DOMAIN,
        "Observation":
        "Inspection of application logging identified that business-critical applications did not generate sufficient audit events to support forensic reconstruction of user activities and security incidents.",
        "Severity": "High"
    },

    {
        "Activity": ACTIVITY,
        "Domain": DOMAIN,
        "Observation":
        "Review of database evidence logging identified that critical database security events including user administration, privilege escalation and schema modifications were not consistently captured for forensic purposes.",
        "Severity": "High"
    },

    {
        "Activity": ACTIVITY,
        "Domain": DOMAIN,
        "Observation":
        "Validation of network logging identified that firewall, router and network security device logs were not centrally collected for correlation and forensic analysis.",
        "Severity": "High"
    },

    {
        "Activity": ACTIVITY,
        "Domain": DOMAIN,
        "Observation":
        "Assessment of endpoint logging identified that security-relevant endpoint events including malware detection, USB device activity and privilege escalation were not consistently captured across managed endpoints.",
        "Severity": "High"
    },

    {
        "Activity": ACTIVITY,
        "Domain": DOMAIN,
        "Observation":
        "Analysis of evidence logging governance identified that high-risk logging gaps remained unresolved beyond approved remediation timelines without documented risk acceptance or compensating controls.",
        "Severity": "High"
    },

    {
        "Activity": ACTIVITY,
        "Domain": DOMAIN,
        "Observation":
        "Verification of operating system logging identified that system startup, shutdown and service failure events were not consistently captured across critical production servers.",
        "Severity": "Medium"
    },

    {
        "Activity": ACTIVITY,
        "Domain": DOMAIN,
        "Observation":
        "Assessment of log coverage identified that security monitoring requirements for newly deployed applications and infrastructure components were not periodically reviewed to ensure adequate forensic evidence generation.",
        "Severity": "Medium"
    },

    {
        "Activity": ACTIVITY,
        "Domain": DOMAIN,
        "Observation":
        "Inspection of event logging identified that security events associated with file access, file deletion and permission modifications were not consistently captured within enterprise logging platforms.",
        "Severity": "Medium"
    },

    {
        "Activity": ACTIVITY,
        "Domain": DOMAIN,
        "Observation":
        "Review of centralized log collection identified that log forwarding failures from critical systems were not periodically monitored, resulting in incomplete forensic evidence repositories.",
        "Severity": "Medium"
    },

    {
        "Activity": ACTIVITY,
        "Domain": DOMAIN,
        "Observation":
        "Validation of evidence capture identified that logging configurations were not periodically reviewed following infrastructure changes, application upgrades or security architecture modifications.",
        "Severity": "Medium"
    },

    {
        "Activity": ACTIVITY,
        "Domain": DOMAIN,
        "Observation":
        "Assessment of forensic readiness identified that logging standards did not define minimum evidence collection requirements for critical business applications and infrastructure components.",
        "Severity": "Medium"
    },

    {
        "Activity": ACTIVITY,
        "Domain": DOMAIN,
        "Observation":
        "Analysis of Evidence Logging & Event Capture governance identified that enterprise evidence logging standards had not undergone periodic review to address evolving threat scenarios, forensic requirements and regulatory expectations.",
        "Severity": "Medium"
    },

        {
        "Activity": ACTIVITY,
        "Domain": DOMAIN,
        "Observation":
        "Verification of evidence logging reviews identified that enterprise logging requirements had not undergone periodic business owner recertification to ensure continued alignment with forensic investigation objectives and regulatory requirements.",
        "Severity": "Medium"
    },

    {
        "Activity": ACTIVITY,
        "Domain": DOMAIN,
        "Observation":
        "Assessment of application evidence logging identified that critical business transactions were not consistently associated with unique transaction identifiers, reducing the ability to reconstruct application activities during forensic investigations.",
        "Severity": "Medium"
    },

    {
        "Activity": ACTIVITY,
        "Domain": DOMAIN,
        "Observation":
        "Analysis of evidence capture identified that security events generated by cloud-hosted infrastructure and platform services were not consistently incorporated into the centralized forensic logging repository.",
        "Severity": "Medium"
    },

    {
        "Activity": ACTIVITY,
        "Domain": DOMAIN,
        "Observation":
        "Inspection of logging configurations identified that changes to audit logging parameters were not themselves captured within security logs, reducing accountability for logging configuration modifications.",
        "Severity": "Medium"
    },

    {
        "Activity": ACTIVITY,
        "Domain": DOMAIN,
        "Observation":
        "Review of evidence logging identified that failed authorization attempts and access denial events were not consistently recorded across critical enterprise applications and supporting infrastructure.",
        "Severity": "Medium"
    },

    {
        "Activity": ACTIVITY,
        "Domain": DOMAIN,
        "Observation":
        "Validation of centralized log collection identified that duplicate, incomplete or malformed log records were not periodically analysed to validate evidence quality and completeness.",
        "Severity": "Medium"
    },

    {
        "Activity": ACTIVITY,
        "Domain": DOMAIN,
        "Observation":
        "Assessment of forensic evidence capture identified that security events generated during scheduled maintenance activities were excluded from centralized logging without documented business justification or risk assessment.",
        "Severity": "Medium"
    },

    {
        "Activity": ACTIVITY,
        "Domain": DOMAIN,
        "Observation":
        "Analysis of evidence logging governance identified that recurring logging deficiencies identified during forensic readiness assessments were not subjected to Root Cause Analysis (RCA) or tracked through formal corrective action plans.",
        "Severity": "Medium"
    },

    {
        "Activity": ACTIVITY,
        "Domain": DOMAIN,
        "Observation":
        "Inspection of forensic documentation identified that evidence source inventories, event mapping documentation and enterprise logging architecture diagrams were not consistently maintained within centralized governance repositories.",
        "Severity": "Medium"
    },

    {
        "Activity": ACTIVITY,
        "Domain": DOMAIN,
        "Observation":
        "Review of management reporting identified that dashboards summarizing evidence collection coverage, logging exceptions, log forwarding failures and unresolved forensic readiness risks were not periodically presented to Information Security management.",
        "Severity": "Medium"
    },

    {
        "Activity": ACTIVITY,
        "Domain": DOMAIN,
        "Observation":
        "Verification of Evidence Logging & Event Capture procedures identified that documented operating procedures had not undergone periodic review and management approval.",
        "Severity": "Low"
    },

    {
        "Activity": ACTIVITY,
        "Domain": DOMAIN,
        "Observation":
        "Assessment of Evidence Logging & Event Capture documentation identified absence of version-controlled enterprise evidence logging standards aligned with the current technology landscape and forensic investigation requirements.",
        "Severity": "Low"
    },

    {
        "Activity": ACTIVITY,
        "Domain": DOMAIN,
        "Observation":
        "Analysis of awareness records identified that system administrators, application owners and security operations personnel were not periodically provided awareness training on enterprise evidence logging requirements and digital forensic readiness principles.",
        "Severity": "Low"
    },

    {
        "Activity": ACTIVITY,
        "Domain": DOMAIN,
        "Observation":
        "Inspection of governance records identified that periodic internal quality assurance reviews over Evidence Logging & Event Capture activities were not evidenced.",
        "Severity": "Low"
    },

    {
        "Activity": ACTIVITY,
        "Domain": DOMAIN,
        "Observation":
        "Review of management reporting identified that enterprise Evidence Logging & Event Capture Key Performance Indicators (KPIs) were not periodically reported to senior management for governance oversight.",
        "Severity": "Low"
    }

]

# ============================================================
# CREATE DATAFRAME
# ============================================================

new_df = pd.DataFrame(OBSERVATIONS)

# ============================================================
# APPEND TO EXISTING REPOSITORY
# ============================================================

combined_df = pd.concat(
    [existing_df, new_df],
    ignore_index=True
)

before_dedup = len(combined_df)

combined_df = combined_df.drop_duplicates(
    subset=[
        "Activity",
        "Domain",
        "Observation"
    ],
    keep="first"
)

duplicates_removed = before_dedup - len(combined_df)

combined_df = combined_df.sort_values(
    by=[
        "Activity",
        "Domain"
    ]
).reset_index(drop=True)

# ============================================================
# SAVE UPDATED REPOSITORY
# ============================================================

combined_df.to_excel(
    DATASET_FILE,
    index=False
)

# ============================================================
# EXECUTION SUMMARY
# ============================================================

print("\n===================================================")
print("DFRA Evidence Logging & Event Capture Library Created Successfully")
print("===================================================")

print(f"\nActivity                : {ACTIVITY}")
print(f"Domain                  : {DOMAIN}")
print(f"Existing Observations   : {existing_count}")
print(f"New Observations        : {len(new_df)}")
print(f"Duplicates Removed      : {duplicates_removed}")
print(f"Final Repository Size   : {len(combined_df)}")

print(f"\nRepository Updated :\n{DATASET_FILE}")