"""
=============================================================
Firewall Security Management Observation Library Builder
=============================================================

Purpose:
--------
Append enterprise-grade Firewall Security Management
observations into the central Observation Repository.

Repository:
dataset/observation_library.xlsx

Author:
B.Tech Major Project
Intelligent Security Analytics
=============================================================
"""

import pandas as pd
from pathlib import Path


# ============================================================
# Configuration
# ============================================================

DOMAIN = "Firewall Security Management"
ACTIVITY = "ITGC"

ROOT_DIR = Path(__file__).resolve().parent.parent

DATASET_FILE = ROOT_DIR / "dataset" / "observation_library.xlsx"


# ============================================================
# Repository Validation
# ============================================================

if not DATASET_FILE.exists():

    raise FileNotFoundError(

        "\nObservation Repository not found.\n\n"
        "Please execute:\n"
        "build_user_management_library.py\n"
        "before running this script."

    )


# ============================================================
# Load Repository
# ============================================================

existing_df = pd.read_excel(DATASET_FILE)

existing_count = len(existing_df)


# ============================================================
# Firewall Security Management Observations
# ============================================================

OBSERVATIONS = [

    {
        "Activity": ACTIVITY,
        "Domain": DOMAIN,
        "Observation":
        "Verification of firewall rule recertification records identified that security rules permitting inbound connectivity to critical production applications had not undergone periodic business owner recertification in accordance with the Enterprise Firewall Security Standard. Failure to periodically validate firewall rule necessity may result in excessive network exposure and unauthorized access paths remaining active.",
        "Severity": "High"
    },

    {
        "Activity": ACTIVITY,
        "Domain": DOMAIN,
        "Observation":
        "Assessment of firewall configuration identified that multiple 'Any Source–Any Destination' access control rules remained enabled within production firewalls without documented business justification or approved compensating controls. Broad access control rules weaken network segmentation and increase the organization's attack surface.",
        "Severity": "High"
    },

    {
        "Activity": ACTIVITY,
        "Domain": DOMAIN,
        "Observation":
        "Analysis of firewall administration identified that privileged firewall administrators possessed unrestricted configuration privileges without implementation of maker-checker approval controls or independent review. Inadequate segregation of duties may increase the risk of unauthorized firewall configuration changes.",
        "Severity": "High"
    },

    {
        "Activity": ACTIVITY,
        "Domain": DOMAIN,
        "Observation":
        "Inspection of firewall change records identified that emergency firewall rule modifications were implemented directly within the production environment without documented post-implementation review or formal management approval. Uncontrolled firewall changes may introduce unauthorized network access paths.",
        "Severity": "High"
    },

    {
        "Activity": ACTIVITY,
        "Domain": DOMAIN,
        "Observation":
        "Review of firewall configuration identified that expired temporary firewall access rules remained active beyond their approved validity period. Failure to remove temporary access rules may result in unnecessary exposure of critical enterprise services.",
        "Severity": "High"
    },

    {
        "Activity": ACTIVITY,
        "Domain": DOMAIN,
        "Observation":
        "Validation of firewall logging configuration identified that security events generated by perimeter firewalls were not consistently forwarded to the centralized Security Information and Event Management (SIEM) platform. Incomplete security event collection may reduce the effectiveness of threat detection and forensic investigations.",
        "Severity": "High"
    },

    {
        "Activity": ACTIVITY,
        "Domain": DOMAIN,
        "Observation":
        "Assessment of firewall high availability identified that failover capability between redundant production firewalls had not been periodically validated through planned resilience testing. Untested failover mechanisms may impact availability of critical business services during firewall failures.",
        "Severity": "High"
    },

    {
        "Activity": ACTIVITY,
        "Domain": DOMAIN,
        "Observation":
        "Analysis of firewall governance identified that high-risk firewall rule exceptions remained active beyond approved review timelines without documented risk acceptance or compensating security controls.",
        "Severity": "High"
    },

    {
        "Activity": ACTIVITY,
        "Domain": DOMAIN,
        "Observation":
        "Verification of firewall rule inventory identified that obsolete and unused firewall rules were not periodically identified and removed from production rule bases.",
        "Severity": "Medium"
    },

    {
        "Activity": ACTIVITY,
        "Domain": DOMAIN,
        "Observation":
        "Assessment of firewall configuration reviews identified redundant and shadowed firewall rules that had not been optimized, increasing rule complexity and reducing administrative efficiency.",
        "Severity": "Medium"
    },

    {
        "Activity": ACTIVITY,
        "Domain": DOMAIN,
        "Observation":
        "Inspection of firewall administration identified that privileged administrative access to firewall management interfaces was not restricted to dedicated administrative management networks.",
        "Severity": "Medium"
    },

    {
        "Activity": ACTIVITY,
        "Domain": DOMAIN,
        "Observation":
        "Review of firewall policy documentation identified that periodic review of inbound and outbound firewall policies was not evidenced for critical production environments.",
        "Severity": "Medium"
    },

    {
        "Activity": ACTIVITY,
        "Domain": DOMAIN,
        "Observation":
        "Validation of firewall monitoring identified that repeated firewall rule violations and denied connection attempts were not periodically analyzed to identify emerging attack patterns.",
        "Severity": "Medium"
    },

    {
        "Activity": ACTIVITY,
        "Domain": DOMAIN,
        "Observation":
        "Assessment of firewall backup procedures identified that periodic backup and restoration testing of production firewall configurations had not been performed.",
        "Severity": "Medium"
    },

    {
        "Activity": ACTIVITY,
        "Domain": DOMAIN,
        "Observation":
        "Analysis of firewall governance identified that the Enterprise Firewall Security Standard had not undergone periodic review to address evolving network security threats and regulatory expectations.",
        "Severity": "Medium"
    },

        {
        "Activity": ACTIVITY,
        "Domain": DOMAIN,
        "Observation":
        "Verification of firewall rule lifecycle identified that firewall rules associated with decommissioned applications remained active within the production environment without documented business justification or formal decommissioning approval. Retention of obsolete firewall rules may unnecessarily increase the enterprise attack surface.",
        "Severity": "Medium"
    },

    {
        "Activity": ACTIVITY,
        "Domain": DOMAIN,
        "Observation":
        "Assessment of firewall rule review identified that outbound firewall rules permitting unrestricted internet connectivity from critical production servers had not undergone periodic business justification and risk assessment.",
        "Severity": "Medium"
    },

    {
        "Activity": ACTIVITY,
        "Domain": DOMAIN,
        "Observation":
        "Analysis of firewall configuration identified that duplicate firewall objects and network groups remained configured within the production rule base, increasing configuration complexity and the likelihood of administrative errors.",
        "Severity": "Medium"
    },

    {
        "Activity": ACTIVITY,
        "Domain": DOMAIN,
        "Observation":
        "Inspection of firewall management identified that concurrent administrative sessions on production firewalls were not monitored or restricted, reducing accountability for privileged configuration changes.",
        "Severity": "Medium"
    },

    {
        "Activity": ACTIVITY,
        "Domain": DOMAIN,
        "Observation":
        "Review of firewall rule implementation identified that newly deployed firewall rules were not subjected to post-implementation validation to confirm that implemented access controls matched approved change requests.",
        "Severity": "Medium"
    },

    {
        "Activity": ACTIVITY,
        "Domain": DOMAIN,
        "Observation":
        "Validation of firewall administration identified that dormant firewall administrator accounts were not periodically identified and disabled following prolonged inactivity.",
        "Severity": "Medium"
    },

    {
        "Activity": ACTIVITY,
        "Domain": DOMAIN,
        "Observation":
        "Assessment of firewall monitoring identified that firewall health parameters including CPU utilization, memory consumption and session capacity were not periodically reviewed for critical perimeter devices.",
        "Severity": "Medium"
    },

    {
        "Activity": ACTIVITY,
        "Domain": DOMAIN,
        "Observation":
        "Analysis of firewall governance identified that recurring firewall policy violations were not subjected to Root Cause Analysis (RCA) or tracked through formal corrective action plans.",
        "Severity": "Medium"
    },

    {
        "Activity": ACTIVITY,
        "Domain": DOMAIN,
        "Observation":
        "Inspection of firewall documentation identified that rule ownership information was not consistently maintained for production firewall policies, reducing accountability for periodic rule recertification.",
        "Severity": "Medium"
    },

    {
        "Activity": ACTIVITY,
        "Domain": DOMAIN,
        "Observation":
        "Review of management reporting identified that dashboards summarizing firewall policy compliance, rule recertification status, unresolved firewall exceptions and configuration health were not periodically presented to Information Security management.",
        "Severity": "Medium"
    },

    {
        "Activity": ACTIVITY,
        "Domain": DOMAIN,
        "Observation":
        "Verification of Firewall Security Management procedures identified that documented operating procedures had not undergone periodic review and management approval.",
        "Severity": "Low"
    },

    {
        "Activity": ACTIVITY,
        "Domain": DOMAIN,
        "Observation":
        "Assessment of Firewall Security Management documentation identified absence of version-controlled firewall security standards aligned with the current enterprise network infrastructure and regulatory requirements.",
        "Severity": "Low"
    },

    {
        "Activity": ACTIVITY,
        "Domain": DOMAIN,
        "Observation":
        "Analysis of awareness records identified that firewall administrators were not periodically provided awareness training on enterprise firewall governance requirements, secure rule management practices and regulatory expectations.",
        "Severity": "Low"
    },

    {
        "Activity": ACTIVITY,
        "Domain": DOMAIN,
        "Observation":
        "Inspection of governance records identified that periodic internal quality assurance reviews over Firewall Security Management activities were not evidenced.",
        "Severity": "Low"
    },

    {
        "Activity": ACTIVITY,
        "Domain": DOMAIN,
        "Observation":
        "Review of management reporting identified that enterprise Firewall Security Management Key Performance Indicators (KPIs) were not periodically reported to senior management for governance oversight.",
        "Severity": "Low"
    }

]

# ============================================================
# CREATE DATAFRAME
# ============================================================

new_df = pd.DataFrame(OBSERVATIONS)

# ============================================================
# APPEND TO EXISTING REPOSITORY
# ============================================================

combined_df = pd.concat(
    [existing_df, new_df],
    ignore_index=True
)

before_dedup = len(combined_df)

combined_df = combined_df.drop_duplicates(
    subset=[
        "Activity",
        "Domain",
        "Observation"
    ],
    keep="first"
)

duplicates_removed = before_dedup - len(combined_df)

combined_df = combined_df.sort_values(
    by=[
        "Activity",
        "Domain"
    ]
).reset_index(drop=True)

# ============================================================
# SAVE UPDATED REPOSITORY
# ============================================================

combined_df.to_excel(
    DATASET_FILE,
    index=False
)

# ============================================================
# EXECUTION SUMMARY
# ============================================================

print("\n===================================================")
print("Firewall Security Management Library Created Successfully")
print("===================================================")

print(f"\nDomain                  : {DOMAIN}")
print(f"Existing Observations   : {existing_count}")
print(f"New Observations        : {len(new_df)}")
print(f"Duplicates Removed      : {duplicates_removed}")
print(f"Final Repository Size   : {len(combined_df)}")

print(f"\nRepository Updated :\n{DATASET_FILE}")