"""
=============================================================
Endpoint Security Management Observation Library Builder
=============================================================

Purpose:
--------
Append enterprise-grade Endpoint Security Management
observations into the central Observation Repository.

Repository:
dataset/observation_library.xlsx

Author:
B.Tech Major Project
Intelligent Security Analytics
=============================================================
"""

import pandas as pd
from pathlib import Path


# ============================================================
# Configuration
# ============================================================

DOMAIN = "Endpoint Security Management"
ACTIVITY = "ITGC"

ROOT_DIR = Path(__file__).resolve().parent.parent

DATASET_FILE = ROOT_DIR / "dataset" / "observation_library.xlsx"


# ============================================================
# Repository Validation
# ============================================================

if not DATASET_FILE.exists():

    raise FileNotFoundError(

        "\nObservation Repository not found.\n\n"
        "Please execute:\n"
        "build_user_management_library.py\n"
        "before running this script."

    )


# ============================================================
# Load Repository
# ============================================================

existing_df = pd.read_excel(DATASET_FILE)

existing_count = len(existing_df)


# ============================================================
# Endpoint Security Management Observations
# ============================================================

OBSERVATIONS = [

    {
        "Activity": ACTIVITY,
        "Domain": DOMAIN,
        "Observation":
        "Verification of endpoint protection coverage identified that multiple production servers were operating without deployment of the organization's approved Endpoint Detection and Response (EDR) solution. Absence of endpoint threat detection reduces the organization's ability to identify and respond to advanced cyber threats.",
        "Severity": "High"
    },

    {
        "Activity": ACTIVITY,
        "Domain": DOMAIN,
        "Observation":
        "Assessment of endpoint hardening identified that local administrator privileges remained assigned to standard users on production workstations contrary to the Enterprise Endpoint Security Standard. Excessive local administrative privileges increase the likelihood of unauthorized software installation and privilege escalation.",
        "Severity": "High"
    },

    {
        "Activity": ACTIVITY,
        "Domain": DOMAIN,
        "Observation":
        "Analysis of endpoint security controls identified that removable media usage was not restricted through centrally managed device control policies, increasing the risk of unauthorized data exfiltration and malware introduction.",
        "Severity": "High"
    },

    {
        "Activity": ACTIVITY,
        "Domain": DOMAIN,
        "Observation":
        "Inspection of endpoint encryption controls identified that full disk encryption was not enabled for critical enterprise laptops storing sensitive organizational information. Absence of disk encryption increases the risk of data disclosure in the event of device loss or theft.",
        "Severity": "High"
    },

    {
        "Activity": ACTIVITY,
        "Domain": DOMAIN,
        "Observation":
        "Review of endpoint security configuration identified that endpoint anti-malware signatures were not automatically updated from approved enterprise repositories, reducing protection against newly emerging malware threats.",
        "Severity": "High"
    },

    {
        "Activity": ACTIVITY,
        "Domain": DOMAIN,
        "Observation":
        "Validation of endpoint monitoring identified that endpoint security alerts generated by EDR solutions were not integrated with the centralized Security Information and Event Management (SIEM) platform. Incomplete alert integration reduces visibility into endpoint security incidents.",
        "Severity": "High"
    },

    {
        "Activity": ACTIVITY,
        "Domain": DOMAIN,
        "Observation":
        "Assessment of endpoint compliance identified that unsupported operating system versions remained deployed on production endpoints without documented risk assessment or compensating security controls. Unsupported platforms increase exposure to unpatched security vulnerabilities.",
        "Severity": "High"
    },

    {
        "Activity": ACTIVITY,
        "Domain": DOMAIN,
        "Observation":
        "Analysis of endpoint governance identified that high-risk endpoint security exceptions remained active beyond approved review timelines without documented management approval or formal risk acceptance.",
        "Severity": "High"
    },

    {
        "Activity": ACTIVITY,
        "Domain": DOMAIN,
        "Observation":
        "Verification of endpoint asset inventory identified that periodic reconciliation between deployed endpoints and the enterprise endpoint management solution was not evidenced.",
        "Severity": "Medium"
    },

    {
        "Activity": ACTIVITY,
        "Domain": DOMAIN,
        "Observation":
        "Assessment of endpoint protection identified that periodic health validation of endpoint protection agents was not performed to ensure successful policy enforcement and malware signature updates.",
        "Severity": "Medium"
    },

    {
        "Activity": ACTIVITY,
        "Domain": DOMAIN,
        "Observation":
        "Inspection of endpoint security configuration identified that application execution control policies were not consistently enforced across production workstations, allowing execution of unauthorized software.",
        "Severity": "Medium"
    },

    {
        "Activity": ACTIVITY,
        "Domain": DOMAIN,
        "Observation":
        "Review of endpoint administration identified that inactive endpoint management agent installations were not periodically identified and remediated, reducing centralized management coverage.",
        "Severity": "Medium"
    },

    {
        "Activity": ACTIVITY,
        "Domain": DOMAIN,
        "Observation":
        "Validation of endpoint monitoring identified that isolated or quarantined endpoints were not periodically reviewed to confirm completion of remediation and secure restoration to the enterprise network.",
        "Severity": "Medium"
    },

    {
        "Activity": ACTIVITY,
        "Domain": DOMAIN,
        "Observation":
        "Assessment of endpoint patch compliance identified that endpoint security baselines were not periodically validated following operating system and application updates.",
        "Severity": "Medium"
    },

    {
        "Activity": ACTIVITY,
        "Domain": DOMAIN,
        "Observation":
        "Analysis of Endpoint Security governance identified that the Enterprise Endpoint Security Standard had not undergone periodic review to address evolving cyber threats, regulatory expectations and technology changes.",
        "Severity": "Medium"
    },

        {
        "Activity": ACTIVITY,
        "Domain": DOMAIN,
        "Observation":
        "Verification of endpoint security reviews identified that endpoint protection policies applied to production servers had not undergone periodic business owner recertification to validate continued compliance with the Enterprise Endpoint Security Standard.",
        "Severity": "Medium"
    },

    {
        "Activity": ACTIVITY,
        "Domain": DOMAIN,
        "Observation":
        "Assessment of endpoint protection identified that endpoint detection and response (EDR) policies were not uniformly enforced across all enterprise-managed endpoints, resulting in inconsistent threat detection capability.",
        "Severity": "Medium"
    },

    {
        "Activity": ACTIVITY,
        "Domain": DOMAIN,
        "Observation":
        "Analysis of endpoint administration identified that endpoint security agents removed or disabled by users were not automatically detected and restored through centralized endpoint management controls.",
        "Severity": "Medium"
    },

    {
        "Activity": ACTIVITY,
        "Domain": DOMAIN,
        "Observation":
        "Inspection of endpoint configuration identified that endpoint firewall policies were not consistently enforced across enterprise workstations, increasing exposure to unauthorized inbound network connections.",
        "Severity": "Medium"
    },

    {
        "Activity": ACTIVITY,
        "Domain": DOMAIN,
        "Observation":
        "Review of endpoint security monitoring identified that repeated malware detection events on enterprise endpoints were not periodically analyzed to identify recurring attack trends or compromised assets.",
        "Severity": "Medium"
    },

    {
        "Activity": ACTIVITY,
        "Domain": DOMAIN,
        "Observation":
        "Validation of endpoint administration identified that local administrator group membership on production endpoints was not periodically reviewed to ensure compliance with the principle of least privilege.",
        "Severity": "Medium"
    },

    {
        "Activity": ACTIVITY,
        "Domain": DOMAIN,
        "Observation":
        "Assessment of endpoint compliance identified that removable media control policies were not periodically validated to ensure enforcement across newly deployed enterprise endpoints.",
        "Severity": "Medium"
    },

    {
        "Activity": ACTIVITY,
        "Domain": DOMAIN,
        "Observation":
        "Analysis of endpoint governance identified that endpoint security incidents requiring endpoint isolation were not subjected to Root Cause Analysis (RCA) or tracked through formal corrective action plans.",
        "Severity": "Medium"
    },

    {
        "Activity": ACTIVITY,
        "Domain": DOMAIN,
        "Observation":
        "Inspection of endpoint documentation identified that ownership information for enterprise-managed endpoints was not consistently maintained within the centralized endpoint management inventory.",
        "Severity": "Medium"
    },

    {
        "Activity": ACTIVITY,
        "Domain": DOMAIN,
        "Observation":
        "Review of management reporting identified that dashboards summarizing endpoint protection coverage, endpoint compliance status, malware detections and unresolved endpoint security risks were not periodically presented to Information Security management.",
        "Severity": "Medium"
    },

    {
        "Activity": ACTIVITY,
        "Domain": DOMAIN,
        "Observation":
        "Verification of Endpoint Security Management procedures identified that documented operating procedures had not undergone periodic review and management approval.",
        "Severity": "Low"
    },

    {
        "Activity": ACTIVITY,
        "Domain": DOMAIN,
        "Observation":
        "Assessment of Endpoint Security Management documentation identified absence of version-controlled endpoint security standards aligned with the current enterprise endpoint landscape and regulatory requirements.",
        "Severity": "Low"
    },

    {
        "Activity": ACTIVITY,
        "Domain": DOMAIN,
        "Observation":
        "Analysis of awareness records identified that endpoint administrators and desktop support personnel were not periodically provided awareness training on enterprise endpoint security requirements, malware response procedures and endpoint protection controls.",
        "Severity": "Low"
    },

    {
        "Activity": ACTIVITY,
        "Domain": DOMAIN,
        "Observation":
        "Inspection of governance records identified that periodic internal quality assurance reviews over Endpoint Security Management activities were not evidenced.",
        "Severity": "Low"
    },

    {
        "Activity": ACTIVITY,
        "Domain": DOMAIN,
        "Observation":
        "Review of management reporting identified that enterprise Endpoint Security Management Key Performance Indicators (KPIs) were not periodically reported to senior management for governance oversight.",
        "Severity": "Low"
    }

]

# ============================================================
# CREATE DATAFRAME
# ============================================================

new_df = pd.DataFrame(OBSERVATIONS)

# ============================================================
# APPEND TO EXISTING REPOSITORY
# ============================================================

combined_df = pd.concat(
    [existing_df, new_df],
    ignore_index=True
)

before_dedup = len(combined_df)

combined_df = combined_df.drop_duplicates(
    subset=[
        "Activity",
        "Domain",
        "Observation"
    ],
    keep="first"
)

duplicates_removed = before_dedup - len(combined_df)

combined_df = combined_df.sort_values(
    by=[
        "Activity",
        "Domain"
    ]
).reset_index(drop=True)

# ============================================================
# SAVE UPDATED REPOSITORY
# ============================================================

combined_df.to_excel(
    DATASET_FILE,
    index=False
)

# ============================================================
# EXECUTION SUMMARY
# ============================================================

print("\n===================================================")
print("Endpoint Security Management Library Created Successfully")
print("===================================================")

print(f"\nDomain                  : {DOMAIN}")
print(f"Existing Observations   : {existing_count}")
print(f"New Observations        : {len(new_df)}")
print(f"Duplicates Removed      : {duplicates_removed}")
print(f"Final Repository Size   : {len(combined_df)}")

print(f"\nRepository Updated :\n{DATASET_FILE}")